stages: [build, analysis, test]

variables: &vars
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  GIT_STRATEGY: none

build:
  stage: build
  before_script: []
  script: docker build -t $IMAGE . && docker push $IMAGE
  tags: [build]
  variables:
    <<: *vars
    GIT_STRATEGY: clone

before_script: [cd /app]

.analysis: &analysis
  stage: analysis
  image: $IMAGE
  tags: [test]

bundle-audit:
  <<: *analysis
  script: bundle exec bundle-audit check --update --ignore CVE-2018-1000544 CVE-2017-8418

rubocop:
  <<: *analysis
  script: bundle exec rubocop lib

.test: &test
  stage: test
  image: $IMAGE
  tags: [test]

rspec:
  <<: *test
  script: bundle exec rspec
