inherit_from:
  - https://raw.githubusercontent.com/ASCTech/rubocop-yml/master/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'node_modules/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Lambda:
  Enabled: false

NestedTernaryOperator:
  Exclude:
    - 'app/controllers/api/v1/admin/custom_fields/values_controller.rb'

PerceivedComplexity:
  Enabled: false